#ifndef HTTP_RESPONSE_CODES_H
#define HTTP_RESPONSE_CODES_H

typedef enum HTTP_RESPONSE_CODE_ENUM
{
    OK = 200,
    ACCEPTED = 202,
    NOT_FOUND = 404,
    INTERNAL_SERVER_ERROR = 500
} HTTP_RESPONSE_CODE;

#endif // HTTP_RESPONSE_CODES_H
